name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .

      - name: Smoke test (import games + run launcher)
        run: |
          source .venv/bin/activate
          python -m games.dice_roller --help || true
          python -m games.number_guess --help || true
          python app.py --help || true
